'use strict';
// Optional development check. Install Playwright separately or set CAW_PLAYWRIGHT_PATH.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CAW_PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(__dirname,'..'),mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'};
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!p.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(p,(err,body)=>{res.writeHead(err?404:200,{'Content-Type':mime[path.extname(p)]||'application/octet-stream'});res.end(err?'Not found':body);});});
(async()=>{let browser;try{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port;
  browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({acceptDownloads:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(url);await page.waitForFunction(()=>document.getElementById('save-status').textContent==='自動保存済み');await page.evaluate(()=>localStorage.setItem('caw_draft_v01',JSON.stringify({schemaVersion:'0.1',appearance:{faceShape:'oval',eyeShape:['round','narrow'],irisColor:'gray',hairColor:'red',height:'tall',molePosition:['neck']}})));await page.reload();
  await page.locator('#face-name').fill('ブラウザ確認の顔');await page.locator('#face-trigger').fill('test_face_x7');await page.locator('.face-workbench details').first().locator('summary').click();
  assert(await page.locator('#face-conflicts').textContent().then(t=>t.includes('同時選択')),JSON.stringify({errors,diagnostic:await page.locator('#face-conflicts').textContent(),stored:await page.evaluate(()=>localStorage.getItem('caw_draft_v01'))}));
  await page.locator('[data-face-layer="eyeShape:narrow"]').selectOption('excluded');assert(!(await page.locator('#output-detailed').textContent()).includes('narrow eyes'));assert((await page.locator('#output-face-negative').textContent()).includes('narrow eyes'));
  await page.locator('[data-face-layer="irisColor:gray"]').selectOption('variable');assert((await page.locator('#output-face-variable').textContent()).includes('gray eyes'));
  await page.locator('[data-face-save]').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('caw_face_library_v1')||'[]').length===1);
  await page.waitForFunction(()=>document.getElementById('save-status').textContent==='自動保存済み');await page.reload();assert.equal(await page.locator('#face-name').inputValue(),'ブラウザ確認の顔');assert((await page.locator('#output-face-pixai').textContent()).startsWith('test_face_x7,'));
  page.on('dialog',d=>d.accept());await page.locator('[data-face-reset]').click();await page.waitForFunction(()=>document.getElementById('face-trigger').value==='');assert(!(await page.locator('#output-detailed').textContent()).includes('oval face'));assert((await page.locator('#output-detailed').textContent()).includes('red hair'));
  await page.locator('[data-face-library]').click();await page.locator('[data-face-apply]').click();assert.equal(await page.locator('#face-trigger').inputValue(),'test_face_x7');assert((await page.locator('#output-detailed').textContent()).includes('red hair'));
  const downloadWait=page.waitForEvent('download');await page.locator('[data-face-export]').click();const download=await downloadWait;const downloaded=await download.path();const profile=JSON.parse(fs.readFileSync(downloaded,'utf8'));assert.equal(profile.faceProfile.triggerWord,'test_face_x7');
  await page.locator('#face-import').setInputFiles({name:'face.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(profile))});await page.waitForFunction(()=>document.getElementById('face-library-dialog').open);await page.locator('[data-face-diff]').first().click();assert((await page.locator('#face-comparison').textContent()).includes('解除：なし'));await page.locator('[data-face-close]').click();
  await page.locator('#face-trigger').fill('second_face_x7');await page.locator('[data-face-new]').click();await page.locator('[data-face-library]').click();await page.locator('[data-face-compare]').click();assert((await page.locator('#face-comparison').textContent()).includes('second_face_x7'));await page.locator('[data-face-close]').click();
  const legacy={schemaVersion:'0.1',appearance:{faceShape:'long',eyeShape:['almond'],browShape:'straight',noseTip:'small',hairColor:'blue'}};await page.locator('#json-import').setInputFiles({name:'old.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});await page.waitForFunction(()=>document.getElementById('output-detailed').textContent.includes('long face'));assert((await page.locator('#output-detailed').textContent()).includes('blue hair'));
  await page.locator('.face-workbench details').first().evaluate(el=>el.open=true);await page.locator('[data-face-preset="adult"]').click();assert(await page.locator('#preset-dialog').isVisible());await page.locator('[data-confirm-preset]').click();assert((await page.locator('#output-face-fixed').textContent()).includes('high cheekbones'));
  await page.locator('details').filter({has:page.locator('#face-view')}).evaluate(el=>el.open=true);await page.locator('#face-view').selectOption('profile');assert((await page.locator('#output-face-check').textContent()).includes('side profile view'));
  const qa=process.env.CAW_QA_DIR||path.join(root,'..','qa');fs.mkdirSync(qa,{recursive:true});
  for(const width of [320,375,768,1280]){await page.setViewportSize({width,height:900});await page.waitForTimeout(300);await page.locator('#face-title').scrollIntoViewIfNeeded();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Horizontal overflow at '+width);await page.screenshot({path:path.join(qa,'face-'+width+'.png')});await page.locator('#face-layers').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(qa,'layers-'+width+'.png')});await page.locator('#face-outputs').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(qa,'outputs-'+width+'.png')});await page.locator('[data-face-library]').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Modal overflow at '+width);await page.locator('[data-face-close]').click();}
  assert.deepEqual(errors,[],'No browser runtime errors');console.log('PASS browser: legacy import, layers, auto-save/reload, save/apply/reset, face JSON, compare, presets, view switching, 320/375/768/1280 layouts; no page errors');
}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}})().catch(err=>{console.error(err);process.exitCode=1;});
